class Text:
    def set_text(self, s: str) -> None: ...
    def set_fontsize(self, size: float | int) -> None: ...
    def set_fontweight(self, weight: str) -> None: ...
    def set_color(self, color: str) -> None: ...
