# Generated by Django 5.2.13 on 2026-04-10 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GridPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_id', models.CharField(max_length=100)),
                ('col_presets', models.JSONField(blank=True, default=dict)),
                ('searches', models.JSONField(blank=True, default=list)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grid_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grid Preference',
                'verbose_name_plural': 'Grid Preferences',
                'unique_together': {('user', 'grid_id')},
            },
        ),
    ]
