"""vNext GridViewSpec type contracts."""

from grid_view_spec.types.a2ui import A2UICatalog, A2UIIntent, A2UIPatch, A2UIPatchOp, A2UISurface
from grid_view_spec.types.actions import (
    GridViewAction,
    GridViewActions,
    GridViewButtonAction,
    GridViewExportAction,
    GridViewLinkAction,
    GridViewMenuAction,
    GridViewOverlayAction,
)
from grid_view_spec.types.assets import GridViewTemplateAsset
from grid_view_spec.types.block_base import BlockType, GridViewBlockBase, GridViewBlockType
from grid_view_spec.types.blocks import GridViewBlock
from grid_view_spec.types.chart_palette import CHART_PALETTE, chart_palette_color
from grid_view_spec.types.chart_server import ChartDataSource, ChartType, KpiAggregate
from grid_view_spec.types.content import (
    ChartOverlayWire,
    ChartSpecWire,
    ColumnFormat,
    GridViewCard,
    GridViewCards,
    GridViewChart,
    GridViewCharts,
    GridViewContent,
    GridViewKpi,
    GridViewTab,
    GridViewTabs,
    GridViewTemplate,
    KpiSpec,
    KpiSpecWire,
    SeriesSpecWire,
)
from grid_view_spec.types.filters_v2 import (
    GridViewFilter,
    GridViewFilterOption,
    GridViewFilters,
    GridViewFilterState,
    GridViewFilterValue,
    GridViewSetPresets,
    SetFilterModel,
)
from grid_view_spec.types.form import (
    GridViewField,
    GridViewFieldCondition,
    GridViewFieldset,
    GridViewForm,
    GridViewValidator,
)
from grid_view_spec.types.header import GridViewEntity, GridViewFact, GridViewHeader
from grid_view_spec.types.host import GridPrefs, GridViewHost, GridViewHostConfig
from grid_view_spec.types.json import JsonScalar, JsonValue, RowDict
from grid_view_spec.types.layout import (
    GridViewArea,
    GridViewLayout,
    GridViewStyle,
    GridViewTrustedStyle,
)
from grid_view_spec.types.lazy import GridViewLazyBlock, GridViewLazyDefaults, GridViewLazyResponse
from grid_view_spec.types.media import (
    GridViewGallery,
    GridViewImage,
    GridViewImageSource,
    GridViewImageVariant,
)
from grid_view_spec.types.nav import GridViewNav, GridViewNavItem
from grid_view_spec.types.overlay import GridViewOverlay
from grid_view_spec.types.result import GridViewDiagnostic, GridViewPolicy, GridViewResult
from grid_view_spec.types.spec import GridViewSpec, GridViewSpecWire
from grid_view_spec.types.spec_meta import GridViewConfig, GridViewMeta
from grid_view_spec.types.table_v2 import (
    ColumnSpecWire,
    GridViewColumn,
    GridViewColumnGroup,
    GridViewColumnSource,
    GridViewDataSource,
    GridViewSort,
    GridViewSortState,
    GridViewTable,
    GridViewTableEdit,
    GridViewTableFooter,
    GridViewTableHeader,
    GridViewTableSettings,
)
from grid_view_spec.types.toolbar import GridViewCounter, GridViewSearch, GridViewToolbar

__all__ = [
    "A2UICatalog",
    "A2UIIntent",
    "A2UIPatch",
    "A2UIPatchOp",
    "A2UISurface",
    "GridPrefs",
    "GridViewAction",
    "GridViewActions",
    "GridViewArea",
    "GridViewBlock",
    "CHART_PALETTE",
    "chart_palette_color",
    "GridViewBlockBase",
    "GridViewBlockType",
    "GridViewButtonAction",
    "GridViewCard",
    "GridViewCards",
    "GridViewChart",
    "GridViewCharts",
    "GridViewColumn",
    "GridViewColumnGroup",
    "GridViewColumnSource",
    "GridViewConfig",
    "GridViewContent",
    "GridViewCounter",
    "GridViewDataSource",
    "GridViewDiagnostic",
    "GridViewEntity",
    "GridViewExportAction",
    "GridViewFact",
    "GridViewField",
    "GridViewFieldCondition",
    "GridViewFieldset",
    "GridViewFilter",
    "GridViewFilterOption",
    "GridViewFilterState",
    "GridViewFilterValue",
    "GridViewFilters",
    "GridViewForm",
    "GridViewGallery",
    "GridViewHeader",
    "GridViewHost",
    "GridViewHostConfig",
    "GridViewImage",
    "GridViewImageSource",
    "GridViewImageVariant",
    "GridViewKpi",
    "GridViewLazyBlock",
    "GridViewLazyDefaults",
    "GridViewLazyResponse",
    "GridViewLayout",
    "GridViewLinkAction",
    "GridViewMenuAction",
    "GridViewMeta",
    "GridViewNav",
    "GridViewNavItem",
    "GridViewOverlay",
    "GridViewOverlayAction",
    "GridViewPolicy",
    "GridViewResult",
    "GridViewSearch",
    "GridViewSetPresets",
    "GridViewSort",
    "GridViewSortState",
    "GridViewSpec",
    "GridViewStyle",
    "GridViewTab",
    "GridViewTable",
    "GridViewTableEdit",
    "GridViewTableFooter",
    "GridViewTableHeader",
    "GridViewTableSettings",
    "GridViewTabs",
    "GridViewTemplate",
    "GridViewTemplateAsset",
    "GridViewToolbar",
    "GridViewTrustedStyle",
    "GridViewValidator",
    "BlockType",
    "ChartDataSource",
    "ChartOverlayWire",
    "ChartSpecWire",
    "ChartType",
    "ColumnFormat",
    "ColumnSpecWire",
    "GridViewSpecWire",
    "JsonScalar",
    "JsonValue",
    "KpiAggregate",
    "KpiSpec",
    "KpiSpecWire",
    "RowDict",
    "SeriesSpecWire",
    "SetFilterModel",
]
