#!/usr/bin/env python3
"""Concatenate user-facing docs into one LLM context bundle."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"
OUT = DOCS / "llm" / "grid-view-spec-llm-context.md"

SOURCES: list[Path] = [
    DOCS / "index.md",
    DOCS / "getting-started.md",
    DOCS / "concepts" / "overview.md",
    DOCS / "concepts" / "data-vs-spec.md",
    DOCS / "concepts" / "backends.md",
    DOCS / "spec" / "index.md",
    DOCS / "spec" / "layout.md",
    DOCS / "spec" / "validation.md",
    DOCS / "blocks" / "index.md",
    DOCS / "blocks" / "composer.md",
    DOCS / "tables" / "index.md",
    DOCS / "tables" / "simple-table.md",
    DOCS / "tables" / "ag-grid.md",
    DOCS / "filtering" / "semantics.md",
    DOCS / "export" / "page-pattern.md",
    DOCS / "reference" / "python-types.md",
    DOCS / "reference" / "template-tags.md",
    DOCS / "reference" / "javascript.md",
    DOCS / "guides" / "i18n.md",
    DOCS / "changelog.md",
]

HEADER = """\
# grid-view-spec — LLM context bundle

> Auto-generated by `scripts/build_llm_context.py`. Do not edit by hand.
> Regenerate: `uv run python scripts/build_llm_context.py`

Package: **grid-view-spec** (PyPI) · Module: **grid_view_spec** · Docs: https://alpiua.github.io/grid-view-spec/

---

"""

_RAW_RE = re.compile(r"^\{%\s*raw\s*%\}\s*\n?|\n?\{%\s*endraw\s*%\}\s*$", re.MULTILINE)


def _strip_raw_wrapper(text: str) -> str:
    text = _RAW_RE.sub("", text)
    return text.strip() + "\n"


def _rel_link_fix(text: str, source: Path) -> str:
    """Flatten relative .md links to section paths for offline reading."""

    def repl(match: re.Match[str]) -> str:
        label, target = match.group(1), match.group(2)
        if target.startswith("http") or target.startswith("#"):
            return match.group(0)
        if target.endswith(".md"):
            try:
                rel = (source.parent / target).resolve().relative_to(DOCS.resolve())
            except ValueError:
                return match.group(0)
            return f"{label} (see section: {rel})"
        return match.group(0)

    return re.sub(r"\[([^\]]+)\]\(([^)]+)\)", repl, text)


def build() -> str:
    parts = [HEADER]
    for path in SOURCES:
        if not path.is_file():
            raise FileNotFoundError(path)
        body = _strip_raw_wrapper(path.read_text(encoding="utf-8"))
        body = _rel_link_fix(body, path)
        rel = path.relative_to(DOCS)
        parts.append(f"\n\n<!-- source: {rel} -->\n\n")
        parts.append(body)
        parts.append("\n\n---\n")
    return "".join(parts)


def main() -> None:
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(build(), encoding="utf-8")
    print(f"Wrote {OUT} ({OUT.stat().st_size:,} bytes)")


if __name__ == "__main__":
    main()
